### ISSUE TITLE
@tiantian-sofia backend `api/scan/transfers` already discard，this repo not suitable https://github.com/itering/subscan-essentials

### ISSUE THREAD

**Issue by tiantian-sofia** [itering/subscan-ui#73]
@tiantian-sofia backend `api/scan/transfers` already discard，this repo not suitable https://github.com/itering/subscan-essentials

_Originally posted by @freehere107 in https://github.com/itering/subscan-ui/issues/72#issuecomment-655902327_

But the URL is still requested by front-end

**Comment by freehere107** [comment]
@tiantian-sofia The front-end repo has outdated
