### ISSUE TITLE
Destination address shown in the UI is different with the destination address from the API

### ISSUE THREAD

**Issue by SleepingNext** [itering/subscan-ui#79]
Hello. I tried to use Subscan API with this link: [https://westend.subscan.io/extrinsic/0xf6d4f309f5e33e5f0fa446341c8281e6b22b34b7014dab89495cce6cdc803316](url) and got a weird destination address on the params: `5e3a6759857c56fb5523b7d0d52e3a0b88d8cc9dd14d8ceabd9b2229b2e2ea73` while the UI shows that the address is: `5ECFi1TMwsvu61UB9VmpiQPDx5TQ12Z8jS7fqzs2CkQEDcMe`. Can you give me some explanations? Thanks in advance!

**Comment by carlhong** [comment]
the `5e3a6759857c56fb5523b7d0d52e3a0b88d8cc9dd14d8ceabd9b2229b2e2ea73` is public key,  the UI show address that transform from public key with prefix. Check out on [https://westend.subscan.io/tools/ss58_transform?input=5e3a6759857c56fb5523b7d0d52e3a0b88d8cc9dd14d8ceabd9b2229b2e2ea73](https://westend.subscan.io/tools/ss58_transform?input=5e3a6759857c56fb5523b7d0d52e3a0b88d8cc9dd14d8ceabd9b2229b2e2ea73)

**Comment by SleepingNext** [comment]
Woah! Thank you very much, @carlhong! You're a lifesaver! Closing.
